// <auto-generated />
using System;
using Laba4._5.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Laba4._5.Storage.Migrations
{
    [DbContext(typeof(HotelDataContext))]
    partial class HotelDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Laba4._5.Storage.Entity.CHnumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnName("gHotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("rooms")
                        .HasColumnName("iRooms")
                        .HasColumnType("int");

                    b.Property<int>("sleep")
                        .HasColumnName("iSleep")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("tblCHnumber");
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NumberId")
                        .HasColumnName("gNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnName("szLname")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("szName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("nights")
                        .HasColumnName("iNights")
                        .HasColumnType("int");

                    b.Property<int>("number")
                        .HasColumnName("iNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NumberId");

                    b.ToTable("tblClient");
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KolNum")
                        .HasColumnName("iKolNum")
                        .HasColumnType("int");

                    b.Property<int>("floors")
                        .HasColumnName("iFloors")
                        .HasColumnType("int");

                    b.Property<int>("kolsot")
                        .HasColumnName("iKolSot")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("szName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblCHhotel");
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.Number", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CHNumberId")
                        .HasColumnName("gCHNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("floor")
                        .HasColumnName("iFloor")
                        .HasColumnType("int");

                    b.Property<int>("nomer")
                        .HasColumnName("iNomer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CHNumberId");

                    b.ToTable("tblNumber");
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("gId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotelId")
                        .HasColumnName("gHotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("dolzhnost")
                        .IsRequired()
                        .HasColumnName("szDolzhnost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnName("szLName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("szName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("tblPersonal");
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.CHnumber", b =>
                {
                    b.HasOne("Laba4._5.Storage.Entity.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.Client", b =>
                {
                    b.HasOne("Laba4._5.Storage.Entity.Number", "Number")
                        .WithMany()
                        .HasForeignKey("NumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.Number", b =>
                {
                    b.HasOne("Laba4._5.Storage.Entity.CHnumber", "CHnumber")
                        .WithMany()
                        .HasForeignKey("CHNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Laba4._5.Storage.Entity.Personal", b =>
                {
                    b.HasOne("Laba4._5.Storage.Entity.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
